### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by NoumanSakhawat**
description missing

### CODE REVIEW

**Comment by nabilfreeman** [comment]
Hey @NoumanSakhawat, thanks! Can you make the description say `Accept Payments with Apple Pay and Android Pay using the Payment Request API.`?

Then I can merge and you get the contributor flag.

**Comment by ARDcode** [comment]
@nabilfreeman https://github.com/naoufal/react-native-payments/pull/260 its a same pullrequest

**Comment by nabilfreeman** [comment]
Thanks @ARDcode - merged #260 so closing this.

What version of Cocoapods do you have? I couldn't replicate this error on my machine which is strange.

**Comment by ARDcode** [comment]
@nabilfreeman cocoapods-1.10.0

**Pull request closed without merging**
