### PR TITLE
Added static PaymentRequest.canMakePaymentsUsingNetworks method

### PR DESCRIPTION
**Pull request by ACOSW**
Added static method PaymentRequest.canMakePaymentsUsingNetworks that allows to detect if user has active cards at Apple Pay.

Reference issue: https://github.com/naoufal/react-native-payments/issues/98

### CODE REVIEW

**Comment by jimmystridh** [comment]
I'm thinking of the Android behaviour; should it perhaps signal that there is something else going on than those payment types not being unavailable. E.g. resolving `undefined` or something more clever ?

**Comment by ACOSW** [comment]
@jimmystridh i thought about it, and now I'm more inclined to opinion that canMakePaymentsUsingNetworks logic should be part of NativePayments.canMakePayments because it does the same thing for android and most likely has an incorrect implementation for iOS.
But on the other side this method should be static because we should have posibility to check payment availability without creation of new PaymenRequest instance. So maybe current PaymentRequest.canMakePaymentsUsingNetworks should be renamed to something like IOScanMakePaymentsUsingNetworks,
Anyway i would like to hear opinion of any of the maintainers about this issue and this pull request, because this functional is very important and it is missing at the moment.

**Comment by jimmystridh** [comment]
Hi @madoke, happy to see some activity for this important library. Are you by any chance publishing a version of your fork to NPM?

**Comment by madoke** [comment]
@jimmystridh yes, we will but it will take some time, I'll let you know when we're ready

**Review by nabilfreeman — APPROVED** [review]
Great work, thanks for your contribution!

**Pull request merged**
